version: "3"

volumes:
  dvwa:


networks:
  dvwa:


services:
  dvwa:
    image: ghcr.io/digininja/dvwa:latest
    environment:
      - DB_SERVER=db
    depends_on:
      - db
    networks:
      - dvwa
    ports:
      # <porta>:<portb> maps porta on the host
      # to portb on the container
      #- 4280:80
      # <ip>:<porta>:<portb> maps porta only on 
      # the interface with that ip to portb on 
      # the container. neat!
      - 127.0.0.1:4280:80
    restart: unless-stopped

  db:
    image: docker.io/library/mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=dvwa
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
    volumes:
      - dvwa:/var/lib/mysql
    networks:
      - dvwa
    restart: unless-stopped
